title: My great simple thing
author: Nataliia Kholopova
email: nataliia.kholopova@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Marvelous description. Better than thin only Garry Potter books can be

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
